CREATE TABLE IF NOT EXISTS inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL NOT NULL DEFAULT 0 CHECK (available_quantity >= 0),
    reserved_quantity INTEGER NOT NULL NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    CONSTRAINT uk_inventories_product_id UNIQUE (product_id)
);